Cadena:
    type: entity
    table: cadena
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        logotipo:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        responsable:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
