Cliente:
    type: entity
    table: cliente
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        !!binary Y29udHJhc2XjsWE=:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: contraseña
        nombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        apellidos:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        telefono:
            type: integer
            nullable: false
            options:
                unsigned: false
        direccion:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        codigoPostal:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: codigo_postal
        nif:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
    lifecycleCallbacks: {  }
