Hotel:
    type: entity
    table: hotel
    indexes:
        id_cadena:
            columns:
                - id_cadena
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        direccion:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        responsable:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        precioHora:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: precio_hora
        codigoPostal:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: codigo_postal
    manyToOne:
        idCadena:
            targetEntity: Cadena
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_cadena:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
